/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.4
 * Generated at: 2021-05-04 21:45:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;

public final class keyfinder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<link href=\"resources/css/main.css\" rel=\"stylesheet\">\n");
      out.write("<script src=\"resources/js/findmykey.js\"></script>\n");
      out.write("<title>No Rest For The Bassist</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<form action=\"keyfinder.jsp\">\n");
      out.write("    <h1>No Rest For The Bassist</h1>\n");
      out.write("    <table>\n");
      out.write("        <tr>\n");
      out.write("            <td style = \"width: 160px;\">\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.html", out, true);
      out.write("\n");
      out.write("            </td>\n");
      out.write("            <td style = \"vertical-align: top\">\n");
      out.write("                <h2>Key Finder</h2>\n");
      out.write("                <table>\n");
      out.write("                    <tr>\n");
      out.write("                        <td style = \"width: 160px;\">\n");
      out.write("                            Notes Hear:\n");
      out.write("                        </td>\n");
      out.write("                        <td style = \"width: 160px;\">\n");
      out.write("                            <select name=\"noteheard1\" id=\"noteheard1\">\n");
      out.write("                                <option value=\"Cnat\" ");
if(((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Cnat")) || (request.getParameter("noteheard1") == null)){ 
      out.write(" selected ");
} 
      out.write(">Note</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Cnat\" ");
if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Cnat")){ 
      out.write(" selected ");
} 
      out.write(">C</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Csharp\" ");
if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Csharp")){ 
      out.write(" selected ");
} 
      out.write(">C#/D♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Dnat\" ");
if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Dnat")){ 
      out.write(" selected ");
} 
      out.write(">D</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Dsharp\" ");
if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Dsharp")){ 
      out.write(" selected ");
} 
      out.write(">D#/E♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Enat\" ");
if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Enat")){ 
      out.write(" selected ");
} 
      out.write(">E</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Fnat\" ");
if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Fnat")){ 
      out.write(" selected ");
} 
      out.write(">F</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Fsharp\" ");
if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Fsharp")){ 
      out.write(" selected ");
} 
      out.write(">F#/G♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Gnat\" ");
if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Gnat")){ 
      out.write(" selected ");
} 
      out.write(">G</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Gsharp\" ");
if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Gsharp")){ 
      out.write(" selected ");
} 
      out.write(">G#/A♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Anat\" ");
if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Anat")){ 
      out.write(" selected ");
} 
      out.write(">A</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Asharp\" ");
if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Asharp")){ 
      out.write(" selected ");
} 
      out.write(">A#/B♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Bnat\" ");
if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Bnat")){ 
      out.write(" selected ");
} 
      out.write(">B</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t<!--  <input type=\"hidden\" id=\"selectednote\" name=\"selectednote\" value=\"\">-->\n");
      out.write("                        </td>\n");
      out.write("                        <td style = \"width: 160px;\">\n");
      out.write("                            <select name=\"noteheard2\" id=\"noteheard2\">\n");
      out.write("                                <option value=\"null\" ");
if(((request.getParameter("noteheard2") != null) && request.getParameter("noteheard2").equals("Cnat")) || (request.getParameter("noteheard2") == null)){ 
      out.write(" selected ");
} 
      out.write(">Note</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Cnat\" ");
if((request.getParameter("noteheard2") != null) && request.getParameter("noteheard2").equals("Cnat")){ 
      out.write(" selected ");
} 
      out.write(">C</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Csharp\" ");
if((request.getParameter("noteheard2") != null) && request.getParameter("noteheard2").equals("Csharp")){ 
      out.write(" selected ");
} 
      out.write(">C#/D♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Dnat\" ");
if((request.getParameter("noteheard2") != null) && request.getParameter("noteheard2").equals("Dnat")){ 
      out.write(" selected ");
} 
      out.write(">D</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Dsharp\" ");
if((request.getParameter("noteheard2") != null) && request.getParameter("noteheard2").equals("Dsharp")){ 
      out.write(" selected ");
} 
      out.write(">D#/E♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Enat\" ");
if((request.getParameter("noteheard2") != null) && request.getParameter("noteheard2").equals("Enat")){ 
      out.write(" selected ");
} 
      out.write(">E</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Fnat\" ");
if((request.getParameter("noteheard2") != null) && request.getParameter("noteheard2").equals("Fnat")){ 
      out.write(" selected ");
} 
      out.write(">F</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Fsharp\" ");
if((request.getParameter("noteheard2") != null) && request.getParameter("noteheard2").equals("Fsharp")){ 
      out.write(" selected ");
} 
      out.write(">F#/G♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Gnat\" ");
if((request.getParameter("noteheard2") != null) && request.getParameter("noteheard2").equals("Gnat")){ 
      out.write(" selected ");
} 
      out.write(">G</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Gsharp\" ");
if((request.getParameter("noteheard2") != null) && request.getParameter("noteheard2").equals("Gsharp")){ 
      out.write(" selected ");
} 
      out.write(">G#/A♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Anat\" ");
if((request.getParameter("noteheard2") != null) && request.getParameter("noteheard2").equals("Anat")){ 
      out.write(" selected ");
} 
      out.write(">A</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Asharp\" ");
if((request.getParameter("noteheard2") != null) && request.getParameter("noteheard2").equals("Asharp")){ 
      out.write(" selected ");
} 
      out.write(">A#/B♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Bnat\" ");
if((request.getParameter("noteheard2") != null) && request.getParameter("noteheard2").equals("Bnat")){ 
      out.write(" selected ");
} 
      out.write(">B</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t<!--  <input type=\"hidden\" id=\"selectednote\" name=\"selectednote\" value=\"\">-->\n");
      out.write("                        </td>\n");
      out.write("                        <td style = \"width: 160px;\">\n");
      out.write("                            <select name=\"noteheard3\" id=\"noteheard3\">\n");
      out.write("                                <option value=\"null\" ");
if(((request.getParameter("noteheard3") != null) && request.getParameter("noteheard3").equals("Cnat")) || (request.getParameter("noteheard3") == null)){ 
      out.write(" selected ");
} 
      out.write(">Note</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Cnat\" ");
if((request.getParameter("noteheard3") != null) && request.getParameter("noteheard3").equals("Cnat")){ 
      out.write(" selected ");
} 
      out.write(">C</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Csharp\" ");
if((request.getParameter("noteheard3") != null) && request.getParameter("noteheard3").equals("Csharp")){ 
      out.write(" selected ");
} 
      out.write(">C#/D♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Dnat\" ");
if((request.getParameter("noteheard3") != null) && request.getParameter("noteheard3").equals("Dnat")){ 
      out.write(" selected ");
} 
      out.write(">D</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Dsharp\" ");
if((request.getParameter("noteheard3") != null) && request.getParameter("noteheard3").equals("Dsharp")){ 
      out.write(" selected ");
} 
      out.write(">D#/E♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Enat\" ");
if((request.getParameter("noteheard3") != null) && request.getParameter("noteheard3").equals("Enat")){ 
      out.write(" selected ");
} 
      out.write(">E</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Fnat\" ");
if((request.getParameter("noteheard3") != null) && request.getParameter("noteheard3").equals("Fnat")){ 
      out.write(" selected ");
} 
      out.write(">F</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Fsharp\" ");
if((request.getParameter("noteheard3") != null) && request.getParameter("noteheard3").equals("Fsharp")){ 
      out.write(" selected ");
} 
      out.write(">F#/G♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Gnat\" ");
if((request.getParameter("noteheard3") != null) && request.getParameter("noteheard3").equals("Gnat")){ 
      out.write(" selected ");
} 
      out.write(">G</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Gsharp\" ");
if((request.getParameter("noteheard3") != null) && request.getParameter("noteheard3").equals("Gsharp")){ 
      out.write(" selected ");
} 
      out.write(">G#/A♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Anat\" ");
if((request.getParameter("noteheard3") != null) && request.getParameter("noteheard3").equals("Anat")){ 
      out.write(" selected ");
} 
      out.write(">A</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Asharp\" ");
if((request.getParameter("noteheard3") != null) && request.getParameter("noteheard3").equals("Asharp")){ 
      out.write(" selected ");
} 
      out.write(">A#/B♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Bnat\" ");
if((request.getParameter("noteheard3") != null) && request.getParameter("noteheard3").equals("Bnat")){ 
      out.write(" selected ");
} 
      out.write(">B</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t<!--  <input type=\"hidden\" id=\"selectednote\" name=\"selectednote\" value=\"\">-->\n");
      out.write("                        </td>\n");
      out.write("                        <td style = \"width: 160px;\">\n");
      out.write("                            <select name=\"noteheard4\" id=\"noteheard4\">\n");
      out.write("                                <option value=\"null\" ");
if(((request.getParameter("noteheard4") != null) && request.getParameter("noteheard4").equals("Cnat")) || (request.getParameter("noteheard4") == null)){ 
      out.write(" selected ");
} 
      out.write(">Note</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Cnat\" ");
if((request.getParameter("noteheard4") != null) && request.getParameter("noteheard4").equals("Cnat")){ 
      out.write(" selected ");
} 
      out.write(">C</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Csharp\" ");
if((request.getParameter("noteheard4") != null) && request.getParameter("noteheard4").equals("Csharp")){ 
      out.write(" selected ");
} 
      out.write(">C#/D♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Dnat\" ");
if((request.getParameter("noteheard4") != null) && request.getParameter("noteheard4").equals("Dnat")){ 
      out.write(" selected ");
} 
      out.write(">D</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Dsharp\" ");
if((request.getParameter("noteheard4") != null) && request.getParameter("noteheard4").equals("Dsharp")){ 
      out.write(" selected ");
} 
      out.write(">D#/E♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Enat\" ");
if((request.getParameter("noteheard4") != null) && request.getParameter("noteheard4").equals("Enat")){ 
      out.write(" selected ");
} 
      out.write(">E</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Fnat\" ");
if((request.getParameter("noteheard4") != null) && request.getParameter("noteheard4").equals("Fnat")){ 
      out.write(" selected ");
} 
      out.write(">F</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Fsharp\" ");
if((request.getParameter("noteheard4") != null) && request.getParameter("noteheard4").equals("Fsharp")){ 
      out.write(" selected ");
} 
      out.write(">F#/G♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Gnat\" ");
if((request.getParameter("noteheard4") != null) && request.getParameter("noteheard4").equals("Gnat")){ 
      out.write(" selected ");
} 
      out.write(">G</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Gsharp\" ");
if((request.getParameter("noteheard4") != null) && request.getParameter("noteheard4").equals("Gsharp")){ 
      out.write(" selected ");
} 
      out.write(">G#/A♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Anat\" ");
if((request.getParameter("noteheard4") != null) && request.getParameter("noteheard4").equals("Anat")){ 
      out.write(" selected ");
} 
      out.write(">A</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Asharp\" ");
if((request.getParameter("noteheard4") != null) && request.getParameter("noteheard4").equals("Asharp")){ 
      out.write(" selected ");
} 
      out.write(">A#/B♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Bnat\" ");
if((request.getParameter("noteheard4") != null) && request.getParameter("noteheard4").equals("Bnat")){ 
      out.write(" selected ");
} 
      out.write(">B</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t<!--  <input type=\"hidden\" id=\"selectednote\" name=\"selectednote\" value=\"\">-->\n");
      out.write("                        </td>\n");
      out.write("                        <td style = \"width: 160px;\">\n");
      out.write("                            <select name=\"noteheard5\" id=\"noteheard5\">\n");
      out.write("                                <option value=\"null\" ");
if(((request.getParameter("noteheard5") != null) && request.getParameter("noteheard5").equals("Cnat")) || (request.getParameter("noteheard5") == null)){ 
      out.write(" selected ");
} 
      out.write(">Note</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Cnat\" ");
if((request.getParameter("noteheard5") != null) && request.getParameter("noteheard5").equals("Cnat")){ 
      out.write(" selected ");
} 
      out.write(">C</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Csharp\" ");
if((request.getParameter("noteheard5") != null) && request.getParameter("noteheard5").equals("Csharp")){ 
      out.write(" selected ");
} 
      out.write(">C#/D♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Dnat\" ");
if((request.getParameter("noteheard5") != null) && request.getParameter("noteheard5").equals("Dnat")){ 
      out.write(" selected ");
} 
      out.write(">D</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Dsharp\" ");
if((request.getParameter("noteheard5") != null) && request.getParameter("noteheard5").equals("Dsharp")){ 
      out.write(" selected ");
} 
      out.write(">D#/E♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Enat\" ");
if((request.getParameter("noteheard5") != null) && request.getParameter("noteheard5").equals("Enat")){ 
      out.write(" selected ");
} 
      out.write(">E</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Fnat\" ");
if((request.getParameter("noteheard5") != null) && request.getParameter("noteheard5").equals("Fnat")){ 
      out.write(" selected ");
} 
      out.write(">F</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Fsharp\" ");
if((request.getParameter("noteheard5") != null) && request.getParameter("noteheard5").equals("Fsharp")){ 
      out.write(" selected ");
} 
      out.write(">F#/G♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Gnat\" ");
if((request.getParameter("noteheard5") != null) && request.getParameter("noteheard5").equals("Gnat")){ 
      out.write(" selected ");
} 
      out.write(">G</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Gsharp\" ");
if((request.getParameter("noteheard5") != null) && request.getParameter("noteheard5").equals("Gsharp")){ 
      out.write(" selected ");
} 
      out.write(">G#/A♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Anat\" ");
if((request.getParameter("noteheard5") != null) && request.getParameter("noteheard5").equals("Anat")){ 
      out.write(" selected ");
} 
      out.write(">A</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Asharp\" ");
if((request.getParameter("noteheard5") != null) && request.getParameter("noteheard5").equals("Asharp")){ 
      out.write(" selected ");
} 
      out.write(">A#/B♭</option>\n");
      out.write("  \t\t\t\t\t\t\t\t<option value=\"Bnat\" ");
if((request.getParameter("noteheard5") != null) && request.getParameter("noteheard5").equals("Bnat")){ 
      out.write(" selected ");
} 
      out.write(">B</option>\n");
      out.write("\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t<!--  <input type=\"hidden\" id=\"selectednote\" name=\"selectednote\" value=\"\">-->\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td>\n");
      out.write("                    Find my Key\n");
      out.write("                    </td>\n");
      out.write("                    <td colspan=\"5\">\n");
      out.write("                     <input type = \"submit\" value = \"GO\" />\n");
      out.write("                    </td>\n");
      out.write("                    <td/>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    \n");
      out.write("                   ");

                   System.out.println("testing what is: " + request.getParameter("noteheard1"));
                   if(((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Cnat")) || (request.getParameter("noteheard1") == null)){ System.out.println("testing cnat note");} 
                   if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Cnat")){ System.out.println("testing cnat");}
  				   if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Csharp")){ System.out.println("testing csharp note");} 
  				   if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Dnat")){ System.out.println("testing dnat note");} 
  				   if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Dsharp")){ System.out.println("testing dsharp note");} 
  				   if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Enat")){ System.out.println("testing enat note");} 
  				   if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Fnat")){System.out.println("testing fnat note");} 
  					if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Fsharp")){ System.out.println("testing fsharp note");} 
  					if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Gnat")){ System.out.println("testing gnat note");} 
  					if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Gsharp")){ System.out.println("testing cnat note");} 
  					if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Anat")){ System.out.println("testing anat note");} 
  					if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Asharp")){ System.out.println("testing asharp note");} 
  					if((request.getParameter("noteheard1") != null) && request.getParameter("noteheard1").equals("Bnat")){System.out.println("testing bnat note");} 
                    
      out.write("\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    ");

                    String reqnote = request.getParameter("noteheard1");
                    System.out.println("reqnote =" +reqnote);
                    String noteClause = "all_notes like '%Cnat%'";
                    if(reqnote != null){
                        System.out.println("not null");
                        noteClause = "all_notes like '%"+reqnote+"%'";
                        
                        String secondNote = request.getParameter("noteheard2");
                        if(secondNote != null && !secondNote.equals("null")){
                        	noteClause += " and all_notes like '%"+secondNote+"%'";
                        }
                        String thirdNote = request.getParameter("noteheard3");
                        if(thirdNote != null && !thirdNote.equals("null")){
                        	noteClause += " and all_notes like '%"+thirdNote+"%'";
                        }
                        
                        String forthNote = request.getParameter("noteheard4");
                        if(forthNote != null && !forthNote.equals("null")){
                        	noteClause += " and all_notes like '%"+forthNote+"%'";
                        }
                        
                        String fifthNote = request.getParameter("noteheard5");
                        if(fifthNote != null && !fifthNote.equals("null")){
                        	noteClause += " and all_notes like '%"+fifthNote+"%'";
                        }
                    }
                    System.out.println("note =" +noteClause);
Class.forName("com.mysql.cj.jdbc.Driver");
Connection conn = DriverManager.getConnection(
    "jdbc:mysql://localhost:3306/norestforthebassist", "root", "Ilike2playbass$");
Statement stmt = conn.createStatement();
ResultSet rsNotes = stmt.executeQuery("select key_name from notes where " + noteClause);
ResultSetMetaData resMetaData = rsNotes.getMetaData();
boolean keyFound = false;

      out.write("\n");
      out.write("                      <td style = \"width: 160px;\">\n");
      out.write("                           Scales it could be:\n");
      out.write("                       </td>\n");
      out.write("                       <td style = \"width: 160px;\" colspan=\"5\">\n");
      out.write("                           <div id=\"scalesitcouldbe\">\n");
      out.write("                           ");

                           
                           while(rsNotes.next()) {
                        	   keyFound = true;
                        	   //out.print(""+nCols);
                        	   out.print(rsNotes.getString("key_name"));
                        	   if(!rsNotes.isLast()){
                        		   out.print(", ");
                        	   }
                        	   //for (int kCol=1; kCol < nCols; kCol++){
                        	//	        out.print("kCol" +kCol);
                        	//		   	out.print(rsNotes.getString(kCol));
                        	//		   }
                           }
                           System.out.println("keyFound:" + keyFound);
                           if(!keyFound){
                        	   out.print("No specific key found, perhaps hearing chromatics.");
                           }
                           
      out.write("\n");
      out.write("                        \t\t\t   </div>\n");
      out.write("                       </td>\n");
      out.write("                    </tr>\n");
      out.write("                </table>\n");
      out.write("            </td>\n");
      out.write("        </tr>\n");
      out.write("    </table>\n");
      out.write("    \n");
      out.write("    </form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
